#access_key_id: $AWS_ACCESS_KEY
#secret_access_key: $AWS_SECRET_KEY
language: generic
notifications:
  email: jalilemail@gmail.com

sudo: required
services:
  - docker

#before tests are run
##build docker image  before test run
before_install:
  - docker build  -t reactapp-test -f Dockerfile.dev .

script:
  - docker run -e CI=true reactapp-test npm run test

    #http://dockerreactapp-env.eba-mrgpguyp.ap-northeast-1.elasticbeanstalk.com/
deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "dockerreactapp"
  env: "DockerReactapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-386357636638"
  #  bucket path is the name of app name:  Namaes usuall get created after you od a your first deploy
  bucket_path: "dockerreactapp"
  on:
    branch: master

  access_key_id: $access_key_id
  secret_access_key:
    secure: "$aws_secret_access_key"
